name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      URL: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      OUTPUT_PATH: nuget.exe

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: make setup

    - name: Run Unit Test
      run: make unittest

    - name: Run Package Build
      run: make package
